# Generated by Django 4.1 on 2022-08-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('living_in', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=10)),
                ('annual_income', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('curr_location', models.CharField(max_length=10)),
                ('ip_address', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=10)),
            ],
        ),
    ]
